services:
  nginx:
    image: nginx:1.28.0
    depends_on:
      - php
    volumes:
      - ./:/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8088:80"
  php:
    image: php:fpm-alpine3.21
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - redis
  redis:
    image: redis:8.0.1
    ports:
      - "6379:6379"
