services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/app
      - ./vendor:/app/vendor
    ports:
      - "8088:8088"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_STORAGE_KEY=statistics_counter
  redis:
    image: redis:8.0.1
    ports:
      - "6379:6379"
