version: "3"

server:
  command: "php src/roadrunner-worker.php"

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 32
    max_jobs: 10000

logs:
  level: warn
  mode: production
  encoding: json
  output: "stderr"

